### PR TITLE
refactor: remove google font dependency, add local font

### PR DESCRIPTION
**Pull request by ayeks**
Google Dependency is kind of risky in EU if you do not request explicit user consent with some shitty cookie banners. Therefor I downloaded the font, added it to the static folder and hardcoded it in the `baseof.html`. It works fine for <https://ayeks.de/> [source](https://gitlab.com/ayeks/ayeksde)

### CODE REVIEW

**Comment by Xennis** [comment]
A workaround for people who are waiting for this:

1. Overwrite the `baseof.html` of the theme: Copy [the version of theme](https://github.com/zerostaticthemes/hugo-winston-theme/blob/master/layouts/_default/baseof.html) to `layouts/_default/baseof.html`. (Note: Consider copying the [license](https://github.com/zerostaticthemes/hugo-winston-theme/blob/master/LICENSE) as well.)

2. Use tools such as https://github.com/majodev/google-webfonts-helper to download the font. You want to download the regular/400 and 700, see https://github.com/zerostaticthemes/hugo-winston-theme/blob/8f29177df250a863ccfbd0191bf20661a32e6a83/layouts/_default/baseof.html#L33 for reference. Save the downloaded fonts in the `static` folder. (Note: Consider attributing it, see https://fonts.google.com/attribution for reference)

3. Replace in the `baseof.html` the Google font loading with the `<style>` shown in the download tool. For getting the URL correct see https://github.com/zerostaticthemes/hugo-winston-theme/blob/8f29177df250a863ccfbd0191bf20661a32e6a83/layouts/_default/baseof.html#L9 as an example.

**Comment by JugglerX** [comment]
Whatever the solution is, it should be more customizable. Some users want Google fonts and it is easier to change the font. Some users will have a lot of difficulty changing local fonts. 

We recently merged a change where custom fonts can be set in the config.

Can we make this work with both google and local fonts?

Maybe we can add @Xennis instructions to the README.md as well?

**Comment by Xennis** [comment]
Hi @JugglerX, I'm not the author of the PR. Still, my suggestion would be:

1. It would be great if the theme gives users the possibility to include custom code into the `<head>` (e.g. a conditional "if file exists" block). 
2. It would be nice if the theme has a parameter to disable Google fonts (e.g. it's enabled by default but can be disabled by some gdpr option).
3. Not merging the PR here. It's rather specific. _If_ users want to include their own fonts there are different ways. Instead, just enable users by 1 and 2 (for having the option). Just one example what I mean with rather specific: The PR here uses the following:

```html
    @font-face {
      font-family: 'Poppins';
      src: url('/Poppins-Bold.ttf')  format('truetype')
    }
  ````
  
If you use the tool mentioned you end up with something like:
  
 ```
/* poppins-regular - latin */
@font-face {
  font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/poppins-v20-latin-regular.woff2') format('woff2'); /* Chrome 36+, Opera 23+, Firefox 39+, Safari 12+, iOS 10+ */
}
 ```
 
 for the "moderns browsers" options. For the "legacy support" it would like like:
 
 
 ```
 /* poppins-regular - latin */
@font-face {
  font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
  font-family: 'Poppins';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/poppins-v20-latin-regular.woff2') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+, Safari 12+, iOS 10+ */
       url('../fonts/poppins-v20-latin-regular.ttf') format('truetype'); /* Chrome 4+, Firefox 3.5+, IE 9+, Safari 3.1+, iOS 4.2+, Android Browser 2.2+ */
}
```

**Comment by ayeks** [comment]
@JugglerX @Xennis Thanks for your comments! I do appreciate the insights. However I am a bit lost with what you guys want as end result for customizable google and local fonts. ;D

If you have some time available please describe the configuration options you want and how the end result should look like. I will see that I transform this into template magic.

Cheers
Lars

**Comment by Xennis** [comment]
From my side (as a user of the theme; I'm not a maintainer etc. here):

> 1. It would be great if the theme gives users the possibility to include custom code into the <head> (e.g. a conditional "if file exists" block).

Here are two examples from other themes: https://github.com/matcornic/hugo-theme-learn/blob/e817f53d690d35f181c896e0e320cb40f797e88c/layouts/partials/header.html#LL41C5-L42C1 and https://github.com/cloudera/hue/blob/07fdafb4d3052de7b5fa77a5d28085bfc9d27e11/docs/docs-site/themes/hugo-theme-learn/layouts/partials/header.html#L36 They are having a partial in the header which allows to easily put custom code (e.g. loading a local font) into the `<head>`.

This could be a separate PR.

> 2. It would be nice if the theme has a parameter to disable Google fonts (e.g. it's enabled by default but can be disabled by some gdpr option).

For example:

```hugo
  {{ if not .Site.Params.disableGoogleFonts }}
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"> 
  {{ end }}
```

So you can turn off via a parameter the loading of Google fonts.

**Comment by JugglerX** [comment]
The latest release allows you to

https://github.com/zerostaticthemes/hugo-winston-theme/blob/master/exampleSite/config.toml#L34 

* specify your fonts in `config.toml` and specify the google fonts url to get the assets. 
* disable google fonts
* had a custom css, head and footer partial which could be used to handle local fonts.

The only case we have not covered via configuration is when a user wants to use locally hosted custom fonts. This involves generating @font-face files and setting the correct paths in the CSS. I'm not sure this can be a simple config option in the config.toml. I worry non technical users will struggle to download fonts, place them in correct folder and set correct paths and that will generate issues.

**Comment by Xennis** [comment]
Thanks, @JugglerX. I just updated to the latest version.

For all people interested here the updated instructions:

A workaround for people who are waiting for this:

1. Use tools such as https://github.com/majodev/google-webfonts-helper to download the font. You want to download the regular/400 and 700, see https://github.com/zerostaticthemes/hugo-winston-theme/blob/8f29177df250a863ccfbd0191bf20661a32e6a83/layouts/_default/baseof.html#L33 for reference. Save the downloaded fonts in the `static` folder. (Note: Consider attributing it, see https://fonts.google.com/attribution for reference)
2. In your `config.toml` set in `params` section `enableGoogleFonts = false`
3. Copy the file [extend-head.html](https://github.com/zerostaticthemes/hugo-winston-theme/blob/219e612defa4e616879813dc9712057aaeab96c2/layouts/partials/extend-head.html) to `layouts/partials/extend-head.html`. Paste here the  `<style>` shown in the download tool. For getting the URL correct see https://github.com/zerostaticthemes/hugo-winston-theme/blob/8f29177df250a863ccfbd0191bf20661a32e6a83/layouts/_default/baseof.html#L9 as an example.

**Pull request closed without merging**
